In [144]:
import numpy as np
import pandas as pd

In [145]:
from sklearn.datasets import load_diabetes

In [146]:
data = load_diabetes()

In [147]:
data.keys()

dict_keys(['data', 'target', 'DESCR', 'feature_names'])

In [148]:
data.DESCR

'Diabetes dataset\n================\n\nNotes\n-----\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\nData Set Characteristics:\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attributes:\n    :Age:\n    :Sex:\n    :Body mass index:\n    :Average blood pressure:\n    :S1:\n    :S2:\n    :S3:\n    :S4:\n    :S5:\n    :S6:\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttp://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efr

In [149]:
data.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [150]:
dataset = pd.DataFrame(data = data.data, columns = data.feature_names)

In [151]:
dataset.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204  
2 -0.002592  0.002864 -0.025930  
3  0.034309  0.022692 -0.009362  
4 -0.002592 -0.031991 -0.046641

In [152]:
X = data.data

In [153]:
y = data.target

In [154]:
from sklearn.cross_validation import train_test_split

In [155]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [156]:
W = np.random.uniform(low=0.1,high=0.1,size=X.shape[1])

In [157]:
W

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [158]:
a = np.ones(X.shape[1]) * 0.1

In [159]:
b = 0.0

In [160]:
a

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [161]:
a = 0.1 #learning rate

In [162]:
epochs = 100000

In [163]:
for i in range(epochs):
    #predictions
    y_pred = (X_train.dot(W)) + b
    #errors
    error = y_train - y_pred
    #mean square error
    mean_sq_error = np.mean(np.square(error))
    #gradient calculation
    w_grad = -(1.0/len(X))*error.dot(X_train) 
    b_grad = -(1.0/len(X))*np.sum(error) 
    #updation
    W = W - w_grad * a
    b = b - b_grad * a
    
    if i % 5000 == 0: print("Epoch %d: %f" % (i, mean_sq_error))

Epoch 0: 29112.761303
Epoch 5000: 3258.074527
Epoch 10000: 3038.172197
Epoch 15000: 2988.239254
Epoch 20000: 2974.345919
Epoch 25000: 2969.708550
Epoch 30000: 2967.855356
Epoch 35000: 2966.957462
Epoch 40000: 2966.421657
Epoch 45000: 2966.034103
Epoch 50000: 2965.711938
Epoch 55000: 2965.421472
Epoch 60000: 2965.148506
Epoch 65000: 2964.886827
Epoch 70000: 2964.633570
Epoch 75000: 2964.387299
Epoch 80000: 2964.147208
Epoch 85000: 2963.912774
Epoch 90000: 2963.683613
Epoch 95000: 2963.459417


In [164]:
W

array([  37.7775766 , -240.06543475,  574.35827391,  403.56762388,
       -157.24934751,  -50.40534742, -229.80758478,  107.57010442,
        404.78754346,  -18.05982291])

In [165]:
np.mean(np.square(error))

2963.2399646566582

In [166]:
y_predict = X_test.dot(W) + b
error = y_test - y_predict
mean_squared_error = np.mean(np.power(error, 2))
print("Mean squared error: %.2f" % mean_squared_error)
print("="*120)

Mean squared error: 2849.26
